//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Listing Item</summary>
	[PublishedModel("listingItem")]
	public partial class ListingItem : PublishedContentModel, IListingControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		public new const string ModelTypeAlias = "listingItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ListingItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public ListingItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Contact: Enter a contact phone number in the following format +45-0000-0000
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("contact")]
		public virtual string Contact => global::Umbraco.Web.PublishedModels.ListingControls.GetContact(this);

		///<summary>
		/// description: Write a few words about the listing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("description")]
		public virtual string Description => global::Umbraco.Web.PublishedModels.ListingControls.GetDescription(this);

		///<summary>
		/// headline: A brief description of the listing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("headline")]
		public virtual string Headline => global::Umbraco.Web.PublishedModels.ListingControls.GetHeadline(this);

		///<summary>
		/// images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("images")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.MediaWithCrops> Images => global::Umbraco.Web.PublishedModels.ListingControls.GetImages(this);

		///<summary>
		/// Listing type: Select if it is for rent, or for sale
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("listingType")]
		public virtual string ListingType => global::Umbraco.Web.PublishedModels.ListingControls.GetListingType(this);

		///<summary>
		/// Price: In DKK. If it is for rent, the monthly price. If it is for sale, the sale price.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("price")]
		public virtual int Price => global::Umbraco.Web.PublishedModels.ListingControls.GetPrice(this);

		///<summary>
		/// region
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("region")]
		public virtual string Region => global::Umbraco.Web.PublishedModels.ListingControls.GetRegion(this);

		///<summary>
		/// Number of Rooms
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("rooms")]
		public virtual int Rooms => global::Umbraco.Web.PublishedModels.ListingControls.GetRooms(this);

		///<summary>
		/// Size: Size of the accomodation in m2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("size")]
		public virtual int Size => global::Umbraco.Web.PublishedModels.ListingControls.GetSize(this);

		///<summary>
		/// Tags: Interesting aspects of the listing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.4")]
		[ImplementPropertyType("tags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Tags => global::Umbraco.Web.PublishedModels.ListingControls.GetTags(this);
	}
}
